- type: job
  parent: AU14JobWorkingJoeBase
  id: AU14JobColonyWorkingJoe
  requirements:
  - !type:RoleTimeRequirement
    role: AU14JobCivilianColonySynthetic
    time: 9000 # 2.5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  icon: "AU14JobIconColonyWorkingJoe"
  spawnMenuRoleName: Working Joe (Colony)
  supervisors: au14-job-supervisors-workingjoe-colony
  usePlayerProfile: false
  hasIcon: false
  accessGroups:
  - auadmin
  - Colonist
  - AUPrisonStaff
  - auwy
  special:
  - !type:AddComponentSpecial
    components:
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - Colony
      - radioWEYU
      - radioCMB
    - type: ActiveRadio
      channels:
      - radioAI
      - Colony
      - radioWEYU
      - radioCMB
    - type: Access
      groups:
      - auadmin
      - Colonist
      - AUPrisonStaff
      - auwy
    - type: Loadout
      prototypes: [ AU14GearColonyWorkingJoe ]
  dummyStartingGear: AU14GearColonyWorkingJoe
  hidden: false

- type: startingGear
  parent: AU14GearWorkingJoeBase
  id: AU14GearColonyWorkingJoe
  equipment:
    id: AU14IDCardColonyWorkingJoe
    ears: AU14HeadsetWorkingJoe
    back: AU14IMPBackpackMarine
    pocket1: AU14StampJoe

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointColonyWorkingJoe
  name: Spawn Point Working Joe (Colony)
  components:
  - type: SpawnPoint
    job_id: AU14JobColonyWorkingJoe
  - type: Sprite
    state: syn_spawn
