- type: job
  parent: CMJobBase
  id: AU14JobWorkingJoeBase
  name: au14-job-name-workingjoe
  description: au14-job-description-workingjoe
  abstract: true
  playTimeTracker: AU14JobWorkingJoe
  basePlaytimeTracker: true
  requireAdminNotify: false
  setPreference: true
  canBeAntag: false
  joinNotifyCrew: false
  roleWeight: 0.25
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  jobEntity: AU14MobWorkingJoe
  jobPreviewEntity: AU14MobWorkingJoeDummy
  hidden: false

- type: startingGear
  id: AU14GearWorkingJoeBase
  equipment:
    shoes: CMBootsBlack
    jumpsuit: CMJumpsuitAverageJoe
    belt: CMBeltUtilityFilled
    back: AU14IMPBackpackMarine
    pocket1: RMCPouchElectronicsFill
    pocket2: RMCPouchConstructionFillFull
  storage:
      belt:
      - AU14MaintenanceJack
      back:
      - AU14SprayCleanerExperimental
      - RMCBucketJanitorial
      - CMMop
      - CMWetSign
      - RMCLightReplacer
      - CMFireExtinguisher
      - AU14StampJoe
  inhand:
  - TrashBag

- type: playTimeTracker
  id: AU14JobWorkingJoe
  isHumanoid: true
