- type: job
  parent: AU14JobMilitaryDoctorBase
  id: AU14JobGOVFORMilitaryDoctor
  name: au14-job-name-govforMilitaryDoctor
  description: au14-job-description-govforMilitaryDoctor
  setPreference: true
  requirements:
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
    - Epilepsy
  ranks:
    #RMCRankCaptain:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORMilitaryDoctor
    #  time: 270000 #75 hours
    RMCRankFirstLT:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORMilitaryDoctor
      time: 86400 #24 hours
    RMCRankSecondLT: []
  startingGear: AU14GearGOVFORMilitaryDoctor
  dummyStartingGear: AU14GearGOVFORMilitaryDoctorDummy
  icon: "AU14JobIconCorpsman"
  requireAdminNotify: true
  spawnMenuRoleName: Military Doctor (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  accessGroups:
  - AU14GovforCorpsman
  - AU14GovforSquad
  access:
  - CMAccessMedical
  - CMAccessChemistry
  overwatchSortPriority: -6
  overwatchShowName: true
  overwatchRoleName: au14-job-name-govforMilitaryDoctor
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetMilitaryDoctor
    - type: JobPrefix
      prefix: au14-job-prefix-govforMilitaryDoctor
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
    - type: UserIFF
      factions:
      - GOVFOR
  hidden: false

- type: startingGear
  id: AU14GearGOVFORMilitaryDoctor
  equipment:
    shoes: CMBootsBlackFilled
    ears: AU14HeadsetGovforAuxiliary
    ears2: RMCM5CameraGear
  inhand:
    - AU14StampMO

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORMilitaryDoctor
  name: Spawn Point GOVFOR Doctor
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORMilitaryDoctor
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORMilitaryDoctorDummy
  equipment:
    shoes: CMBootsBlackFilled
    back: CMSatchelMarine
