- type: job
  abstract: true
  parent: AU14JobWorkingJoeBase
  id: AU14JobGOVFORWorkingJoeBase
  icon: "AU14JobIconGovWorkingJoe"
  spawnMenuRoleName: Working Joe (GOVFOR)
  supervisors: au14-job-supervisors-workingjoe-military
  startingGear: AU14GearGOVFORWorkingJoe
  dummyStartingGear: AU14GearGOVFORWorkingJoe
  usePlayerProfile: false
  jobEntity: AU14MobWorkingJoeGOVFOR
  accessGroups:
  - AU14GovforCommand
  - AUPrisonStaff
  - auwy

- type: job
  parent: AU14JobGOVFORWorkingJoeBase
  id: AU14JobGOVFORWorkingJoe
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  special:
  - !type:AddComponentSpecial
    components:
    - type: UserIFF
      factions:
      - GOVFOR
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - radioGovforCommand
      - radioGovforJTAC
      - radioGovforAlpha
      - radioGovforCharlie
      - radioGovforBravo
      - radioGovforIntel
      - radioGovforMILP
    - type: ActiveRadio
      channels:
      - radioAI
      - radioGovforCommand
      - radioGovforJTAC
      - radioGovforAlpha
      - radioGovforCharlie
      - radioGovforBravo
      - radioGovforIntel
      - radioGovforMILP
    - type: Tag
      tags:
      - WorkingJoe
      - CanPilot
      - FootstepSound
      - DoorBumpOpener

- type: startingGear
  parent: AU14GearWorkingJoeBase
  id: AU14GearGOVFORWorkingJoe
  equipment:
    id: AU14IDCardGOVFORWorkingJoe
    ears: AU14HeadsetWorkingJoe
    ears2: RMCM5CameraGear
    back: AU14IMPBackpackMarine
    pocket1: AU14StampJoe

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORWorkingJoe
  name: Spawn Point Working Joe (GOVFOR)
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORWorkingJoe
  - type: Sprite
    state: syn_spawn
