- type: job
  parent: AU14JobadvisorBase
  id: AU14JobGOVFORadvisor
  name: au14-job-name-govforadvisor
  description: au14-job-description-govforadvisor
  setPreference: true
  canBeAntag: false
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # Set to 72000 once we are fully launched AU14 todo
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankSergeantMajor:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 360000 # 100 hours
    RMCRankMasterGunnerySergeant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORadvisor
      time: 86400 # 24 hours
    #RMCRankFirstSergeant:
    #- !type:RoleTimeRequirement
    #  role: AU14JobGOVFORadvisor
    #  time: 43200 # 12 hours
    RMCRankFirstSergeant: []
  startingGear: AU14GearGOVFORadvisor
  dummyStartingGear: AU14GearGOVFORadvisorDummy
  icon: "AU14JobIconGovAdvisor"
  requireAdminNotify: true
  spawnMenuRoleName: Platoon Advisor (GOVFOR)
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-govfor
  whitelisted: true
  accessGroups:
  - AU14GovforCommand
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
    - type: Skills
      preset: AU14SkillPresetPlatoonAdvisor
    - type: JobPrefix
      prefix: au14-job-prefix-govforadvisor
    - type: SeeNewPlayers
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: UserIFF
      factions:
      - GOVFOR
    - type: MarineOrders
      moveOrderSoundMale:
        collection: AU14MaleMoveOrder
      moveOrderSoundFemale:
        collection: AU14FemaleMoveOrder
      focusOrderSoundMale:
        collection: AU14MaleFocusOrder
      focusOrderSoundFemale:
        collection: AU14FemaleFocusOrder
      holdOrderSoundMale:
        collection: AU14MaleHoldOrder
      holdOrderSoundFemale:
        collection: AU14FemaleHoldOrder
  hidden: false

- type: startingGear
  id: AU14GearGOVFORadvisor
  equipment:
    id: AU14IDCardSquadAdvisor
    ears: AU14HeadsetGovforCommand
    back: AU14SatchelMarineAdvisorMilitary
  inhand:
    -  AU14StampSEA

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORadvisor
  name: Spawn Point GOVFOR Advisor
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORadvisor
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearGOVFORadvisorDummy
  equipment:
    shoes: CMBootsBrownFilled
    head: CMHeadCapDrill
    jumpsuit: CMJumpsuitBO
    ears: AU14HeadsetGovforCommand
