# ├──[ colony ]──────────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCivilianColonist
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianColonyAdministrator
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianColonyAdminAssistant
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianFoodServiceWorker
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianJournalist
  points: 7
  groups:
  - JournalistSpecializationAU14
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - ForceJournalistEssentialAU14

- type: roleLoadout
  id: JobAU14JobCivilianKellandWarden
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - ForceKellandWardenEssentialAU14

- type: roleLoadout
  id: JobAU14JobCivilianMiner
  points: 7
  groups:
  - MinerSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianEngineer
  points: 7
  groups:
  - EngiSatchelAU14
  - EngiJacketAU14
  - EngiGlovesAU14
  - EngiBeltAU14
  - EngiPouchAU14
  - EngiPouchRightAU14
  - ForceStampApprovedAU14
  - ForceSynthResetKeyAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianForeman
  points: 7
  groups:
  - EngiSatchelAU14
  - EngiJacketAU14
  - EngiGlovesAU14
  - EngiBeltAU14
  - EngiPouchAU14
  - EngiPouchRightAU14
  - ForceStampApprovedAU14
  - ForceSynthResetKeyAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianWasteManagementSpecialist
  points: 7
  groups:
  - EngiSatchelAU14
  - EngiBeltAU14
  - EngiPouchAU14
  - EngiPouchRightAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianFreightSystemsSpecialist
  points: 7
  groups:
  - EngiSatchelAU14
  - EngiJacketAU14
  - EngiGlovesAU14
  - EngiBeltAU14
  - EngiPouchAU14
  - EngiPouchRightAU14
  - MedPouchAU14
  - MedPouchRightAU14
  - EROPouchAU14
  - EROPouchRightAU14
  - ForceStampApprovedAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianNurse
  points: 7
  groups:
  - MedBackpackAU14
  - MedJumpsuitAU14
  - MedHatsAU14
  - MedJacketAU14
  - MedGlovesAU14
  - CivFootwearAU14
  - MedMaskAU14
  - MedBeltAU14
  - MedPouchAU14
  - MedPouchRightAU14
  - ForceMedEssentialAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianPhysician
  points: 7
  groups:
  - CivilianPhysicianSpecializationAU14
  - MedBackpackAU14
  - MedJumpsuitAU14
  - MedHatsAU14
  - MedJacketAU14
  - MedGlovesAU14
  - CivFootwearAU14
  - MedMaskAU14
  - MedBeltAU14
  - MedPouchAU14
  - MedPouchRightAU14
  - ForceMedEssentialAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianEmergencyResponseOfficer
  points: 7
  groups:
  - EROSpecializationAU14
  - CivSatchelAU14
  - EROJumpsuitAU14
  - EROJacketAU14
  - EROSuitSpecialAU14
  - EROGlovesAU14
  - EROMaskAU14
  - EROHatsAU14
  - EROPouchAU14
  - EROPouchRightAU14
  - CivFootwearAU14
  - EROBeltAU14
  - ForceEROEssentialAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianUSASFRecruiter
  points: 7
  groups:
  - CivSatchelAU14
  - RecruiterSpecializationAU14
  - RecruiterHatsAU14
  - RecruiterJumpsuitAU14
  - RecruiterPatchesAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ corporate ]───────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCivilianCorporateLiaison
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - WYCLJumpsuitAU14
  - WYCLOuterwearAU14
  - WYCLHeadwearAU14
  - WYCLFootwearAU14
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianLaselleLiaison
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianCorporateAssistant
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobWYGuard
  points: 7
  groups:
  - PaperworkRMC
  - WYGuardJumpsuitAU14
  - WYGuardLeftPouchAU14
  - WYGuardRightPouchAU14
  - WYGuardHeadwearAU14
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianScientist
  points: 7
  groups:
  - MedGlovesAU14
  - MedMaskAU14
  - ScientistPouchAU14
  - ScientistPouchRightAU14
  - MedBackpackAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ COS ]─────────────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCivilianColonySynthetic
  points: 7
  groups:
  - ColonySynthSpecializationAU14
  - ColonySynthUniformAU14
  - ColonySynthPouchesLeftAU14
  - ColonySynthPouchesRightAU14
  - ColonySynthSuitSpecialAU14
  - ColonySynthBeltAU14
  - SynthGlovesAU14
  - SynthBackpackAU14
  - SynthEquipmentAU14
  - SynthGlassesAU14
  - SynthMasksAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ orbital ]─────────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobColonyPilot
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianOrbitalManager
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianOrbitalSecurity
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ ambassadors ]─────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCivilianAmbassadorICSC
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianAmbassadorUPP
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianAmbassadorUA
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianAmbassadorTWE
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCivilianAmbassadorCCA
  points: 7
  groups:
  - CivSatchelAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

# ├──[ CLF ]─────────────────────────────────────────────────────────┤
- type: roleLoadout
  id: JobAU14JobCLFCellLeader
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCLFGuerilla
  points: 7
  groups:
  - CivSatchelAU14
  - CivFootwearAU14
  - CivJumpsuitAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCLFPhysician
  points: 7
  groups:
  - CLFPhycisianSpecializationAU14
  - MedBackpackAU14
  - MedJumpsuitAU14
  - MedHatsAU14
  - MedJacketAU14
  - MedGlovesAU14
  - CivFootwearAU14
  - MedMaskAU14
  - MedBeltAU14
  - MedPouchAU14
  - MedPouchRightAU14
  - ForceMedEssentialAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobCLFSurgeon
  points: 7
  groups:
  - MedBackpackAU14
  - MedJumpsuitAU14
  - MedHatsAU14
  - MedJacketAU14
  - MedGlovesAU14
  - CivFootwearAU14
  - MedMaskAU14
  - MedBeltAU14
  - MedPouchAU14
  - MedPouchRightAU14
  - ForceMedEssentialAU14
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
