- type: roleLoadout
  id: JobAU14JobGOVFORadvisor
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobGOVFORPlatCo
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - GOVFORPlatCOSidearmBeltAU14

- type: roleLoadout
  id: JobAU14JobGOVFORPlatOp
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobGOVFORSectionSergeant
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORSquadSergeant
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobGOVFORRadioTelephoneOperator
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORMilitaryDoctor
  points: 7
  groups:
  - GOVFORDoctorEquipmentAU14
  - GOVFORDoctorUniformAU14
  - MedJacketMilitaryAU14
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORPlatoonCorpsman
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORSquadAutomaticRifleman
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORSquadCombatTech
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORSquadRifleman
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMC
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORDSPilot
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC
  - WeaponsRMC

- type: roleLoadout
  id: JobAU14JobGOVFORDCC
  points: 7
  groups:
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORAuxTech
  points: 7
  groups:
  - GOVFORAuxTechClothingAU14
  - MarineBackpack
  - EyewearRMCPVE
  - MasksRMCPVE
  - HeadwearRMCPVE
  - HelmetGarbsRMCPVE
  - PaperworkRMC
  - RecreationalRMC
  - CannedDrinksAU14
  - SmokablesRMC

- type: roleLoadout
  id: JobAU14JobGOVFORAuxSupportSynth
  points: 7
  groups:
  - GOVFORSynthSpecializationAU14
  - SynthBackpackAU14
  - SynthBeltAU14
  - SynthPouchesLeftAU14
  - SynthPouchesRightAU14
  - SynthGlovesAU14
  - SynthHeadwearAU14
  - SynthGlassesAU14
  - SynthUniformAU14
  - SynthUniformAccessoriesRMC
  - SynthSuitAU14
  - SynthSuitSpecialAU14
  - SynthEquipmentAU14
  - SynthShoesRMC
  - SynthMasksAU14
  - PaperworkRMC
  - RecreationalRMC
  - HelmetGarbsRMC
  - SmokablesRMC
  - ForceStampApprovedAU14
  - ForceSynthResetKeyAU14
  - SynthAccesoriesSpecialAU14
