# COS Specizalizations

- type: loadout
  id: ColonySyntheticSpecializationDefaultAU14
  equipment:
    id: AU14IDCardColonySynthetic

- type: loadout
  id: ColonySyntheticSpecializationEngineeringAU14
  equipment:
    id: AU14IDCardColonySyntheticEngineering

- type: loadout
  id: ColonySyntheticSpecializationMedicalAU14
  equipment:
    id: AU14IDCardColonySyntheticMedical

- type: loadout
  id: ColonySyntheticSpecializationCommandAU14
  equipment:
    id: AU14IDCardColonySyntheticCommand

# GOVFOR Doctor Specializations

- type: loadout
  id: GOVFORDoctorSpecializationDefaultAU14
  equipment:
    id: AU14IDCardGOVFORDoctor

- type: loadout
  id: GOVFORDoctorSpecializationSurgeonAU14
  equipment:
    id: AU14IDCardGOVFORDoctorSurgeon

- type: loadout
  id: GOVFORDoctorSpecializationPharmacistAU14
  equipment:
    id: AU14IDCardGOVFORDoctorPharmacist

- type: loadout
  id: GOVFORDoctorSpecializationMorticianAU14
  equipment:
    id: AU14IDCardGOVFORDoctorMortician

# GOVFOR Synth Specializations
- type: loadout
  id: GOVFORSynthSpecializationDefaultAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynth

- type: loadout
  id: GOVFORSynthSpecializationEngineeringAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynthEngineering

- type: loadout
  id: GOVFORSynthSpecializationMedicalAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynthMedical

- type: loadout
  id: GOVFORSynthSpecializationSecurityAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynthSecurity

- type: loadout
  id: GOVFORSynthSpecializationCommandAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynthCommand

- type: loadout
  id: GOVFORSynthSpecializationIntelAU14
  equipment:
    id: AU14IDCardGOVFORAuxSupportSynthIntel

# OPFOR Synth Specializations

# backpacks

- type: loadout
  id: SmarpackAU14
  equipment:
    back: RMCSmartpack

- type: loadout
  id: SmarpackBlackAU14
  equipment:
    back: RMCSmartpackBlack

- type: loadout
  id: SmarpackGreenAU14
  equipment:
    back: RMCSmartpackGreen

- type: loadout
  id: SmarpackWhiteAU14
  equipment:
    back: RMCSmartpackWhite

- type: loadout
  id: SmarpackTanAU14
  equipment:
    back: RMCSmartpackTan

- type: loadout
  id: SmarpackA1TanAU14
  equipment:
    back: RMCSmartpackA1Tan

- type: loadout
  id: SmarpackA1GreenAU14
  equipment:
    back: RMCSmartpackA1Green

- type: loadout
  id: SmarpackA1BlackAU14
  equipment:
    back: RMCSmartpackA1Black

- type: loadout
  id: SmarpackA1AU14
  equipment:
    back: RMCSmartpackA1

- type: loadout
  id: SmarpackA1WhiteAU14
  equipment:
    back: RMCSmartpackA1White

# jumpsuits

- type: loadout
  id: CivilianBoilerSuitDarkBlueSynthAU14
  equipment:
    jumpsuit: AU14CivilianBoilerSuitDarkBlueSynth

# pouches

- type: loadout
  id: PouchToolsFilledSupportSyntheticAU14
  equipment:
    pocket1: AU14PouchToolsFilledSupportSynthetic

- type: loadout
  id: PouchPoliceEquipmentSupportSynthAU14
  equipment:
    pocket1: AU14PouchPoliceEquipmentSupportSynth

- type: loadout
  id: PouchCommandFillAU14
  equipment:
    pocket1: AU14PouchCommandFill

- type: loadout
  id: PouchDocumentAU14
  equipment:
    pocket1: RMCPouchDocument

- type: loadout
  id: PouchSlingAU14
  equipment:
    pocket1: AU14PouchSlingBinocs

- type: loadout
  id: PouchAutoinjectorFilledMilitaryDoctorAU14
  equipment:
    pocket1: AU14PouchAutoinjectorFilledMilitaryDoctor

- type: loadout
  id: PouchConstructionFillFullAU14
  equipment:
    pocket1: RMCPouchConstructionFillFull

- type: loadout
  id: PouchMedkitPMCFilledAU14
  equipment:
    pocket1: RMCPouchMedkitPMCFilled

# pocket2

- type: loadout
  id: PouchToolsFilledSupportSyntheticRightAU14
  equipment:
    pocket2: AU14PouchToolsFilledSupportSynthetic

- type: loadout
  id: PouchPoliceEquipmentSupportSynthRightAU14
  equipment:
    pocket2: AU14PouchPoliceEquipmentSupportSynth

- type: loadout
  id: PouchCommandFillRightAU14
  equipment:
    pocket2: AU14PouchCommandFill

- type: loadout
  id: PouchDocumentRightAU14
  equipment:
    pocket2: RMCPouchDocument

- type: loadout
  id: PouchSlingRightAU14
  equipment:
    pocket2: AU14PouchSlingBinocs

- type: loadout
  id: PouchAutoinjectorFilledMilitaryDoctorRightAU14
  equipment:
    pocket2: AU14PouchAutoinjectorFilledMilitaryDoctor

- type: loadout
  id: PouchConstructionFillFullRightAU14
  equipment:
    pocket2: RMCPouchConstructionFillFull

- type: loadout
  id: PouchMedkitPMCFilledRightAU14
  equipment:
    pocket2: RMCPouchMedkitPMCFilled

# belt

- type: loadout
  id: BeltMedicBagSupportSynthAU14
  equipment:
    belt: AU14BeltMedicBagSupportSynth

- type: loadout
  id: BeltMedicBagRMCSupporSynthAU14
  equipment:
    belt: AU14BeltMedicBagSupportSynthRMC

- type: loadout
  id: BeltMedicBagBlackSupportSynthAU14
  equipment:
    belt: AU14BeltMedicBagSupportSynthBlack

- type: loadout
  id: BeltHolsterNailgunFillAU14
  equipment:
    belt: RMCBeltHolsterNailgunFill

# suits

- type: loadout
  id: ArmorM3VLSynthAU14
  equipment:
    outerClothing: CMArmorM3VLSynth

- type: loadout
  id: ArmorM3VLSynthClassicAU14
  equipment:
    outerClothing: CMArmorM3VLSynthClassic

- type: loadout
  id: ArmorM3VLSynthDesertAU14
  equipment:
    outerClothing: CMArmorM3VLSynthDesert

- type: loadout
  id: ArmorM3VLSynthJungleAU14
  equipment:
    outerClothing: CMArmorM3VLSynthJungle

- type: loadout
  id: ArmorM3VLSynthSnowAU14
  equipment:
    outerClothing: CMArmorM3VLSynthSnow

- type: loadout
  id: ArmorM3VLSynthUrbanAU14
  equipment:
    outerClothing: CMArmorM3VLSynthUrban

# equipment
- type: loadout
  id: MaintenanceJackAU14
  inhand:
  - AU14MaintenanceJack

- type: loadout
  id: SynthBreachingHammerAU14
  inhand:
  - RMCSynthBreachingHammer

- type: loadout
  id: PortableDialysisAU14
  inhand:
  - RMCPortableDialysis

- type: loadout
  id: AU14SprayCleanerExperimentalAU14
  inhand:
  - AU14SprayCleanerExperimental
# Civilian Synth Specializations
