- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobadvisorBaseAbstract
  name: au14-job-name-govforadvisor
  description: au14-job-description-govforadvisor
  icon: "AU14JobIconGovAdvisor"
  spawnMenuRoleName: Platoon Advisor (GOVFOR)
  startingGear: AU14GearGOVFORadvisor
  dummyStartingGear: AU14GearGOVFORadvisorDummy
  playTimeTracker: AU14JobGOVFORadvisor
  requireAdminNotify: true
  whitelisted: true
  canBeAntag: false
  accessGroups:
  - AU14GovforCommand
  - aulegacygroupcommand

- type: job
  abstract: true
  parent: AU14JobadvisorBaseAbstract
  id: AU14JobadvisorBase
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600
  - !type:AgeRequirement
    requiredAge: 21
  - !type:TraitsRequirement
    inverted: true
    traits:
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankSergeantMajor:
      entity: AU14ChevronUSCMSergeantMajor
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORadvisor
        time: 360000
    RMCRankMasterGunnerySergeant:
      entity: AU14ChevronUSCMMasterGunnerySergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORadvisor
        time: 86400
    RMCRankFirstSergeant:
      entity: AU14ChevronUSCMFirstSergeant
      requirements: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: SeeNewPlayers
    - type: Skills
      preset: AU14SkillPresetPlatoonAdvisor
    - type: RMCSpeechBubbleSpecificStyle
      speechStyleClass: commanderSpeech
    - type: JobPrefix
      prefix: au14-job-prefix-govforadvisor
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_advisor

- type: playTimeTracker
  id: AU14JobGOVFORadvisor
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORadvisor
  equipment:
    id: AU14IDCardSquadAdvisor
    ears: AU14HeadsetGovforCommand
    back: AU14SatchelMarineAdvisorMilitary # removed by ImaginaryFriend
    pocket1: AU14StampSEA # removed by ImaginaryFriend

- type: startingGear
  id: AU14GearGOVFORadvisorDummy
  equipment:
    shoes: CMBootsBrownFilled
    head: CMHeadCapDrill
    jumpsuit: CMJumpsuitBO
    ears: AU14HeadsetGovforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORadvisor
  name: Spawn Point GOVFOR Advisor
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORadvisor
  - type: Sprite
    state: syn_spawn
