- type: job
  parent: CMJobBase
  id: AU14JobDCCBase
  name: au14-job-name-govfordcc
  description: au14-job-description-govfordcc
  playTimeTracker: AU14JobGOVFORDCC
  basePlaytimeTracker: true
  hidden: true
  inheritAddComponentSpecials: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: govfor
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: dcc

- type: playTimeTracker
  id: AU14JobGOVFORDCC
  isHumanoid: true
