- type: job
  abstract: true
  parent: AU14JobMilitaryBase
  id: AU14JobSquadSergeantBaseAbstract # Squad Leader Abstraction
  name: au14-job-name-govforsquadsergeant
  description: au14-job-description-govforsquadsergeant
  icon: "AU14JobIconSarge"
  spawnMenuRoleName: Squad Sergeant (GOVFOR)
  startingGear: AU14GearGOVFORSquadSergeant
  dummyStartingGear: AU14GearGOVFORSquadSergeantDummy
  playTimeTracker: AU14JobGOVFORSquadSergeant
  overwatchRoleName: Squad Lead
  overwatchShowName: true
  overwatchSortPriority: -5
  canBeAntag: false
  accessGroups:
  - AU14GovforFTL

- type: job
  abstract: true
  parent: AU14JobSquadSergeantBaseAbstract
  id: AU14JobSquadSergeantBase # Squad Leader Base
  requirements:
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  ranks:
    RMCRankCivilian: []
  chevrons:
    RMCRankStaffSergeant:
      entity: AU14ChevronUSCMStaffSergeant
      requirements:
      - !type:RoleTimeRequirement
        role: AU14JobGOVFORSquadSergeant
        time: 36000 # 10 hours
    RMCRankSergeant:
      entity: AU14ChevronUSCMSergeant
      requirements: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      preset: AU14SkillPresetPlatoonSergeant
    - type: RMCSpeechBubbleSpecificStyle
      speechStyleClass: commanderSpeech
    - type: JobPrefix
      prefix: au14-job-prefix-govforsquadsergeant
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14govforhud.rsi
        state: govfor_sergeant

- type: playTimeTracker
  id: AU14JobGOVFORSquadSergeant
  isHumanoid: true

- type: startingGear
  id: AU14GearGOVFORSquadSergeant
  equipment:
    id: AU14IDCardSquadSergeant
    ears: AU14HeadsetGovforCommand

- type: startingGear
  id: AU14GearGOVFORSquadSergeantDummy
  equipment:
    outerClothing: AU14ArmorM3JungleOne
    shoes: CMBootsBrown
    head: AU14JungleBoonieHat
    jumpsuit: AU14JungleFatigues
    earss: AU14HeadsetGovforCommand

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointGOVFORSquadSergeant
  name: Spawn Point GOVFOR Squad Sergeant
  components:
  - type: SpawnPoint
    job_id: AU14JobGOVFORSquadSergeant
  - type: Sprite
    state: syn_spawn
