- type: job
  parent: CMJobBase
  id: AU14JobSquadAutomaticRiflemanBase
  name: au14-job-name-govforsquadautomaticrifleman
  description: au14-job-description-govforsquadautomaticrifleman
  playTimeTracker: AU14JobGOVFORSquadAutomaticRifleman
  basePlaytimeTracker: true
  hidden: true
  inheritAddComponentSpecials: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: govfor
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: smartgunner

- type: playTimeTracker
  id: AU14JobGOVFORSquadAutomaticRifleman
  isHumanoid: true
