- type: job
  parent: CMJobBase
  id: AU14JobSquadCombatTechBase
  name: au14-job-name-govforsquadcombattech
  description: au14-job-description-govforsquadcombattech
  playTimeTracker: AU14JobGOVFORSquadCombatTech
  basePlaytimeTracker: true
  hidden: true
  inheritAddComponentSpecials: true
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: govfor
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: engi

- type: playTimeTracker
  id: AU14JobGOVFORSquadCombatTech
  isHumanoid: true
