- type: job
  parent: AU14JobSquadAutomaticRiflemanBase
  id: AU14JobOpforSquadAutomaticRifleman
  name: au14-job-name-opforsquadautomaticrifleman
  description: au14-job-description-opforsquadautomaticrifleman
  icon: "AU14JobIconOPFORAFN"
  spawnMenuRoleName: Automatic Rifleman (OPFOR)
  supervisors: au14-job-supervisors-opfor
  startingGear: AU14GearopforSquadAutomaticRifleman
  dummyStartingGear: AU14GearopforAutoRiflemanDummy
  accessGroups:
  - AU14OpforGunner
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: opfor
    - type: UserIFF
      factions:
      - OPFOR
    - type: NpcFactionMember
      factions:
      - OPFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_AU14/Interface/au14opforhud.rsi
        state: afn

- type: startingGear
  id: AU14GearopforSquadAutomaticRifleman
  equipment:
    id: AU14IDCardopforSquadAutomaticRifleman
    ears: AU14HeadsetOpforMarine

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointopforSquadAutomaticRifleman
  name: Spawn Point opfor Squad Rifleman
  components:
  - type: SpawnPoint
    job_id: AU14JobOpforSquadAutomaticRifleman
  - type: Sprite
    state: syn_spawn

- type: startingGear
  id: AU14GearopforAutoRiflemanDummy
  equipment:
    outerClothing: AU14ArmorSmartGunJungleCombatHarness
    shoes: AU14BootsJungle
    head: AU14JungleM10Helmet
    jumpsuit: AU14JungleFatigues
    ears: AU14HeadsetOpforMarine
