- type: job
  abstract: true
  parent: AU14JobWorkingJoeBase
  id: AU14JobOPFORWorkingJoeBase
  icon: "AU14JobIconOPFORWorkingJoe"
  spawnMenuRoleName: Working Joe (OPFOR)
  supervisors: au14-job-supervisors-workingjoe-military
  startingGear: AU14GearOPFORWorkingJoe
  dummyStartingGear: AU14GearOPFORWorkingJoe
  usePlayerProfile: false
  jobEntity: AU14MobWorkingJoeOPFOR
  accessGroups:
  - AU14OpforCommand
  - AUPrisonStaff
  - auwy

- type: job
  parent: AU14JobOPFORWorkingJoeBase
  id: AU14JobOPFORWorkingJoe
  hidden: true
  requirements:
  - !type:RoleTimeRequirement
    role: AU14JobGOVFORAuxSupportSynth
    time: 9000 # 2.5 hours
  - !type:TraitsRequirement
    inverted: true
    traits:
    - SocialAnxietyHeavy
    - FrontalLisp
    - NonResuscitable
    - Epilepsy
  special:
  - !type:AddComponentSpecial
    components:
    - type: UserIFF
      factions:
      - OPFOR
    - type: IntrinsicRadioTransmitter
      channels:
      - radioAI
      - radioOpforAlpha
      - radioOpforCommand
      - radioOpforCharlie
      - radioOpforBravo
      - radioOpforIntel
      - radioOpforJTAC
    - type: ActiveRadio
      channels:
      - radioAI
      - radioOpforAlpha
      - radioOpforCommand
      - radioOpforCharlie
      - radioOpforBravo
      - radioOpforIntel
      - radioOpforJTAC
    - type: Tag
      tags:
      - WorkingJoe
      - CanPilot
      - FootstepSound
      - DoorBumpOpener

- type: startingGear
  parent: AU14GearWorkingJoeBase
  id: AU14GearOPFORWorkingJoe
  equipment:
    id: AU14IDCardOPFORWorkingJoe
    ears: AU14HeadsetWorkingJoe
    ears2: RMCM5CameraGear
    back: AU14IMPBackpackMarine
    pocket1: AU14StampJoe

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointOPFORWorkingJoe
  name: Spawn Point Working Joe (OPFOR)
  components:
  - type: SpawnPoint
    job_id: AU14JobOPFORWorkingJoe
  - type: Sprite
    state: syn_spawn
