- type: job
  parent: CMJobBase
  id: AU14JobCivilianHeadPhysician
  name: au14-job-name-civilianheadphysician
  description: au14-job-description-civilianheadphysician
  setPreference: true
  canBeAntag: false
  playTimeTracker: AU14JobCivilianHeadPhysician
  requirements:
  - !type:DepartmentTimeRequirement
    department: AU14DepartmentColonyMedical
    time: 36000 # 10 hours
  - !type:OverallPlaytimeRequirement
    time: 86400 # 24 hours
  - !type:AgeRequirement
    requiredAge: 25
  - !type:TraitsRequirement
    inverted: true
    traits:
    - NonResuscitable
  ranks:
    RMCRankCivilianDoctor: []
  startingGear: AU14GearCivilianHeadPhysician
  icon: "AU14JobIconColonyHeadPhysician"
  hasIcon: false
  requireAdminNotify: false
  joinNotifyCrew: false
  supervisors: au14-job-supervisors-colonyadministrator
  accessGroups:
  - Colonist
  - aumed
  - AUPrisonStaff
  - auheadsofcolony
  access:
# - AU14AccessColonyHeadPhysician # implicit
  - AU14AccessColonyAdministrator
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillMedical: 4
        RMCSkillResearch: 2
        RMCSkillSurgery: 3
        RMCSkillFirearms: 2
    - type: JobPrefix
      prefix: au14-job-prefix-headphysician
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
  hidden: false

- type: startingGear
  id: AU14GearCivilianHeadPhysician
  equipment:
    id: AU14IDCardColonyHeadPhysician
    jumpsuit: RMCScrubsLightBlue
    shoes: RMCShoesBlack
    outerClothing: RMCLabcoatOpened
    pocket1: AU14StampHPHY

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianHeadPhysician
  name: Spawn Point Head Physician
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianHeadPhysician
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianHeadPhysician
  isHumanoid: true
