- type: job
  parent: CMJobBase
  id: AU14JobCivilianAmbassadorCCA
  name: au14-job-name-civilianambassadorcca
  description: au14-job-description-civilianambassadorcca
  playTimeTracker: AU14JobCivilianAmbassadorCCA
  setPreference: true
  ranks:
    AU14RankAmbassador: []
  startingGear: AU14GearCivilianAmbassadorCCA
  icon: "AU14JobIconCCAAmbassador"
  requireAdminNotify: false
  joinNotifyCrew: false
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  supervisors: au14-job-supervisors-orbital
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  access:
  - AU14AccessColonyAmbassador
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
        RMCSkillIntel: 1
        RMCSkillOverwatch: 1
    - type: CMVendorUser
      id: AU14JobCivilianCorporateLiaison
      points: 70
    - type: JobPrefix
      prefix: au14-job-prefix-civilianambassadorcca
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
  hidden: false

- type: startingGear
  id: AU14GearCivilianAmbassadorCCA
  equipment:
    jumpsuit: AU14CivilianWorkwearYellow
    shoes: RMCShoesLaceupBrown
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: AU14CivilianJacketTanPufferVest
    ears: AU14ColonyAdminHeadset
    pocket1: AU14StampCCAA
  inhand:
  - RMCPortableVendorCorporate

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianAmbassadorCCA
  name: Spawn Point Civilian CCA Ambassador
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianAmbassadorCCA
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianAmbassadorCCA
  isHumanoid: true
