- type: job
  parent: CMJobBase
  id: AU14JobCivilianAmbassadorUA
  name: au14-job-name-civilianambassadorua
  description: au14-job-description-civilianambassadorua
  playTimeTracker: AU14JobCivilianAmbassadorUA
  setPreference: true
  ranks:
    AU14RankAmbassador: []
  startingGear: AU14GearCivilianAmbassadorUA
  icon: "AU14JobIconUAAmbassador"
  requireAdminNotify: false
  joinNotifyCrew: false
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  supervisors: au14-job-supervisors-orbital
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  access:
  - AU14AccessColonyAmbassador
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
        RMCSkillIntel: 1
        RMCSkillOverwatch: 1
    - type: CMVendorUser
      id: AU14JobCivilianCorporateLiaison
      points: 70
    - type: JobPrefix
      prefix: au14-job-prefix-civilianambassadorua
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
  hidden: false

- type: startingGear
  id: AU14GearCivilianAmbassadorUA
  equipment:
    jumpsuit: CMJumpsuitLiaisonBlack
    shoes: RMCShoesLaceupBrown
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: RMCFancySuitJacketBrown
    ears: AU14AmbassadorUAHeadset
    pocket1: AU14StampUAA
  inhand:
  - RMCPortableVendorCorporate

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianAmbassadorUA
  name: Spawn Point Civilian UA Ambassador
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianAmbassadorUA
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianAmbassadorUA
  isHumanoid: true
