- type: job
  parent: CMJobBase
  id: AU14JobCivilianAmbassadorUPP
  name: au14-job-name-civilianambassadorupp
  description: au14-job-description-civilianambassadorupp
  playTimeTracker: AU14JobCivilianAmbassadorUPP
  setPreference: true
  ranks:
    AU14RankAmbassador: []
  startingGear: AU14GearCivilianAmbassadorUPP
  icon: "AU14JobIconUPPAmbassador"
  requireAdminNotify: false
  joinNotifyCrew: false
  whitelisted: true
  whitelistParent: AU14JobGeneralWhitelist
  supervisors: au14-job-supervisors-orbital
  accessGroups:
  - Colonist
  - auadmin
  - AUPrisonStaff
  access:
  - AU14AccessColonyAmbassador
  roleWeight: 0.25
  special:
  - !type:AddComponentSpecial
    components:
    - type: Skills
      skills:
        RMCSkillFireman: 1
        RMCSkillVehicles: 1
        RMCSkillDomestics: 1
        RMCSkillFirearms: 1
        RMCSkillIntel: 1
        RMCSkillOverwatch: 1
    - type: CMVendorUser
      id: AU14JobCivilianCorporateLiaison
      points: 70
    - type: JobPrefix
      prefix: au14-job-prefix-civilianambassadorupp
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: synth
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: Marine
      Faction: govfor
  hidden: false

- type: startingGear
  id: AU14GearCivilianAmbassadorUPP
  equipment:
    jumpsuit: CMJumpsuitSPPCiv4
    shoes: RMCShoesLaceupBrown
    id: AU14IDCardColonyCorporateLiaison
    outerClothing: RMCCoatSPP
    ears: AU14AmbassadorUPPHeadset
    pocket1: AU14StampUPPA
  inhand:
  - RMCPortableVendorCorporate

- type: entity
  parent: CMSpawnPointJobBase
  id: AU14SpawnPointCivilianAmbassadorUPP
  name: Spawn Point Civilian UPP Ambassador
  components:
  - type: SpawnPoint
    job_id: AU14JobCivilianAmbassadorUPP
  - type: Sprite
    state: syn_spawn

- type: playTimeTracker
  id: AU14JobCivilianAmbassadorUPP
  isHumanoid: true
