- type: job
  parent: AU14JobDSPilotBase
  id: AU14JobGOVFORDSPilotRMC
  name: RMC Pilot Officer
  spawnMenuRoleName: Pilot Officer (TWE RMC)
  startingGear: AU14GearGOVFORDSPilot
  dummyStartingGear: AU14GearGOVFORDSPilotDummy
  ranks:
    RMC_Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 360000 # 100 hours
    RMC_2Lieutenant:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 216000 # 60 hours
    RMC_WarrantOfficer1:
    - !type:RoleTimeRequirement
      role: AU14JobGOVFORDSPilot
      time: 108000 # 30 hours
    RMC_WarrantOfficer2: []
  special:
  - !type:AddComponentSpecial
    components:
    - type: Marine
      Faction: govfor
    - type: NpcFactionMember
      factions:
      - GOVFOR
    - type: UserIFF
      factions:
      - GOVFOR
    - type: TacticalMapIcon
      icon:
        sprite: /Textures/_RMC14/Interface/map_blips.rsi
        state: pilot
    - type: Skills
      skills:
        RMCSkillFirearms: 2
        RMCSkillFireman: 1
        RMCSkillIntel: 1
        RMCSkillJtac: 2
        RMCSkillLeadership: 1
        RMCSkillMedical: 2
        RMCSkillOverwatch: 1
        RMCSkillPilot: 2
        RMCSkillPowerLoader: 2
        RMCSkillSurgery: 1
        RMCSkillPolice: 1
    - type: JobPrefix
      prefix: au14-job-prefix-govfordspilotRMC
